# Generated by Django 4.2.28 on 2026-02-18 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WEATHERAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_records', to='WEATHERAPP.city')),
            ],
            options={
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-searched_at'],
            },
        ),
    ]
