# Generated by Django 4.2.28 on 2026-02-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField(blank=True, null=True)),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('weather_main', models.CharField(max_length=100)),
                ('weather_description', models.CharField(max_length=255)),
                ('wind_speed', models.FloatField()),
                ('cloudiness', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='WEATHERAPP.city')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
