# Generated by Django 4.2.28 on 2026-02-18 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WEATHERAPP', '0002_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='aqi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='rain_probability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='sunrise',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='sunset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='temp_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='temp_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='uvi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='visibility',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_deg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_gust',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='WEATHERAPP.city')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
